[SonicWallpaperRule]
Description=Sonic Wallpaper desktop-layer window rule
acceptfocusrule=2
below=true
belowrule=2
noborder=true
noborderrule=2
skiptaskbar=true
skiptaskbarrule=2
wmclass=Sonic
wmclassmatch=2

[General]
count=1
rules=SonicWallpaperRule
